### ISSUE TITLE
[SR-10476] CGPoint, CGSize, CGRect are Hashable in corelibs-Foundation, but not in Cocoa Foundation

### ISSUE THREAD

**Issue by lorentey** [swiftlang/swift-corelibs-foundation#3443]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10476      |
   |Radar             | rdar://problem/49869189         |
   |Original Reporter | @lorentey      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 8d8d2dac4371a503bd685407e30d08d3

  </details>

**Issue Description:**

CGPoint, CGSize and CGRect are declared Hashable in swift-corelibs-foundation, while they're only Equatable in the Core Graphics overlay.

Similarly, NSEdgeInsets is declared Hashable in swift-corelibs-foundation, while it's not even Equatable on Apple platforms.

**Comment by KYHyeon** [comment]
CGSize finally conforms Hashable from iOS18!
