### ISSUE TITLE
[SR-9493] NSAttributedString Leaks

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift-corelibs-foundation#3574]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9493      |
   |Radar             | rdar://46674511         |
   |Original Reporter | Mahdi.Makhdumi (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963069-9088ee4c-1f6b-414f-bb7b-66695fb318a2.gz)

      
<details>
  <summary>Environment</summary>

macOS High Sierra 10.13.6

Xcode version 10.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug, Leak        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2d60476a48e451a1c7db0c786d26aab1

  </details>

**Issue Description:**

I'm trying to convert html to string using NSAttributedString, everything works fine, but I found that using this initializer causes a leaks in memory.

``` swift
init(data: Data, options: [NSAttributedString.DocumentReadingOptionKey : Any] = [:], documentAttributes dict: AutoreleasingUnsafeMutablePointer<NSDictionary?>?) throws 
```

<img src="Screen Shot 2018-12-13 at 1.18.04 AM.png" class="thumbnail" />

What I've tried at first:

``` swift
let data = "<p>test</p>".data(using: .utf8)!
 _ = try! NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html], documentAttributes: nil)
```

Result:  
<img src="Screen Shot 2018-12-13 at 1.06.34 AM.png" class="thumbnail" />

after doing some research, I taught maybe autoreleasepool can fix it, so I've tried again:

``` swift
autoreleasepool{
    let data = "<p>test</p>".data(using: .utf8)!
    for _ in 1...1000 {
        _ = try! NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html], documentAttributes: nil)
    }
}
```

Result: again I got leaks.  
<img src="Screen Shot 2018-12-13 at 1.13.11 AM.png" class="thumbnail" />

<img src="Screen Shot 2018-12-13 at 1.12.42 AM.png" class="thumbnail" />

**Comment by mohamedfarid1993** [comment]
Hey, Is there a solution for this ?

**Comment by dxshindeo** [comment]
Waiting for solution as well. This breaks the purpose of instrumentation.

**Comment by rahulkhatrirws** [comment]
Its been 4 years. No solution yet?

**Comment by jaikrishna-zuper** [comment]
Any workaround or solutions to fix the memory leak

**Comment by erfanandesta1373** [comment]
Any workaround?

**Comment by VeretennikovSV** [comment]
Is there any solution?

**Comment by KoCMoHaBTa** [comment]
In my case, using the following code in a UIViewRepresentable, even without capturing anything in the closure, was causing all State/Environment objects referenced by the View to leak

```swift
NSMutableAttributedString.loadFromHTML(string: text) { result, _, error in 
}
```

Managed to workaround it by switching to Swift Concurrency

```swift
Task {
  let (result, _) = try await NSMutableAttributedString.fromHTML(text)
}
```

**Comment by parkera** [comment]
Note: Even on Darwin, this HTML API comes from AppKit or UIKit - not from the Foundation framework itself.

**Comment by ksvslk** [comment]
So, any workarounds for displaying HTML text?
You can see the beautiful memory increase when moving to view which uses `NSAttributedString` 

![Screenshot 2024-12-05 at 13 13 59](https://github.com/user-attachments/assets/4d316648-7332-4283-9f5f-a063ed71d2cd)

**Comment by parkera** [comment]
I think this is the wrong place to track this issue, unfortunately. As I mentioned - the implementation is not part of Foundation even on Darwin platforms. It should be tracked via a feedback issue. The one mentioned above (rdar://46674511) is closed, so a new one may be appropriate and directed towards the TextKit component.
