### ISSUE TITLE
Calendar's CoW is broken.

### ISSUE THREAD

**Issue by sidepelican** [swiftlang/swift-corelibs-foundation#4630]
## Problem

`Calendar`'s some functions is not guarded with CoW.

`Calendar` wraps `NSCalendar` and it uses `_applyMutation` for any mutating actions.
but next two functions on `NSCalendar` mutates itself in the function. This behavior slips through the CoW.

https://github.com/apple/swift-corelibs-foundation/blob/d248649df1fd102269c0ba312220a1922b4f8bec/Sources/Foundation/NSCalendar.swift#L490-L509

https://github.com/apple/swift-corelibs-foundation/blob/d248649df1fd102269c0ba312220a1922b4f8bec/Sources/Foundation/NSCalendar.swift#L756-L762

When we use these functions in another thread using copied `Calendar`, may cause unexpected behavior.

## How to reproduce

Run this code in Linux environemnt. 
Sometimes prints `"bug!"` or sometimes crashes.

```swift
import Foundation

func main() {
    var calendar = Calendar(identifier: .gregorian)
    calendar.timeZone = TimeZone(secondsFromGMT: 9 * 3600)!

    let now = Date()
    let expected: Int = calendar.component(.hour, from: now)

    f(calendar) // Copy the calendar here and use it in backgrount thread.

    for _ in 0...100_000 {
        let v = calendar.component(.hour, from: now)
        if v != expected {
            print("bug! expected=\(expected), actual=\(v)")
        }
    }
    print("end")
}

func f(_ calendar: Calendar) {
    let comps = DateComponents(
        timeZone: TimeZone(secondsFromGMT: 0)!,
        year: 2022, month: 9, day: 1
    )

    DispatchQueue.global().async {
        for _ in 0...100_000 {
            _ = calendar.date(from: comps)
        }
    }
}

main()
```

## Expected

`Calendar`'s CoW works right.
I know `Calendar` is not thread safe unlike the Apple platform. This issue focuses abount CoW.

**Comment by parkera** [comment]
You're right about this. Part of the issue is that ICU's `ucal` is itself not thread safe, so it needs to be wrapped with a lock at a higher level.

**Comment by parkera** [comment]
Thank you for checking!
