### ISSUE TITLE
Memory crash at String._bridgeToObjectiveCImpl()

### ISSUE THREAD

**Issue by NehaPundlik** [swiftlang/swift-corelibs-foundation#5130]
I'll describe my crash with an example, looking for some insights into the reason why this is happening.

```
@objc public protocol LauncherContainer {
  var launcher: Launcher { get }
}

@objc public protocol Launcher: UIViewControllerTransitioningDelegate {
  func initiateLaunch(url: URL, launchingHotInstance: Bool)
}

@objc final class LauncherContainer: NSObject, LauncherContainer, TabsContentCellTapHandler {
...
  init(
    ...
  ) {
    ...
    super.init()
  }

  ...

  //
  // ContentCellTapHandler
  //
  public func tabContentCellItemDidTap(
    tabId: String
  ) {
    ...
    launcher.initiateNewTabNavigation(
      tabId: tabId      // Crash happens here
    )
}

public class Launcher: NSObject, Launcher, FooterPillTapHandler {
  public func initiateNewTabNavigation(tabId: String) {
     ...
  }
}

public protocol TabsContentCellTapHandler: NSObject {
  func tabContentCellItemDidTap(
    tabId: String,
}
```

1. Crash stack last 2 lines are- libswiftCore.dylib swift_unknownObjectRetain libswiftCore.dylib String._bridgeToObjectiveCImpl()
String._bridgeToObjectiveCImpl() gets called when the caller and implementation is in Swift file
2. I believe due to @objc class LauncherContainer there'd be bridging header generated. Does that mean tabId passed to tabContentCellItemDidTap is a String but the one passed to initiateNewTabNavigation is NSString?
3. TabId is UUID().uuidString if that helps. Wondering if UUID().uuidString has something to do with this.

Thanks a ton for helping.

**Comment by NehaPundlik** [comment]
@phausler Sorry for proactively tagging you, thought you might be able to help me with the above question.

**Comment by parkera** [comment]
Apologies @NehaPundlik but I don't think this is the correct place for this question. I think the Apple Developer Forums, and including info like a crash log with a backtrace will help.
